version: '3.8'

services:
  # Frontend React
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: thontrangliennhat-frontend
    restart: always
    environment:
      - REACT_APP_BASE_URL=https://api.thontrangliennhat.com/api
      - REACT_APP_UPLOAD_URL=https://api.thontrangliennhat.com/uploads
      - REACT_APP_PUBLIC_URL=https://thontrangliennhat.com
    networks:
      - thontrangliennhat-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`thontrangliennhat.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  # Backend API Node.js
  api:
    build:
      context: ../phunongbuondon-api
      dockerfile: Dockerfile
    container_name: thontrangliennhat-api
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
      - JWT_SECRET=jHdBu8Tgq3pL5vR7xZ2AsSw9Kf1YmN4EcX6QoWzDnV0OpI8M
      - CORS_ORIGIN=https://thontrangliennhat.com
      - UPLOAD_DIR=public/uploads
      - IMAGE_DIR=public/images
    volumes:
      - api-uploads:/app/public/uploads
      - api-images:/app/public/images
    networks:
      - thontrangliennhat-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.thontrangliennhat.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

  # Traefik reverse proxy
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/acme.json:/acme.json
    networks:
      - thontrangliennhat-network

networks:
  thontrangliennhat-network:
    driver: bridge

volumes:
  api-uploads:
  api-images: 